### ISSUE TITLE
Error messages with "Error {}" are hard to debug

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/localdev-issues#1]
We got a few reports of customers receiving an unhelpful error attempting to initialize a site:

```
Failed after 5 retries with backoff 500 and error {}
```

Users with this issue should update to the latest (`0.3.x` or better) release and try again. At worst, we'll get a more meaningful error message.

**Comment by joshkoenig** [comment]
This specific issue is fixed, but surfacing the real problem which is that some of the error messages don't provide enough information to debug, and also break our error indexing process.

**Comment by pirog** [comment]
@joshkoenig i think the "indexing" part of this is just a default value type mismatch. 

In terms of getting more info to debug or verifying the above "indexing" issue, i think im going to need more info on what exactly you are seeing.

i'll keep this open so we can discuss that, but i'll also fix the "default value type mismatch" since thats a good change regardless of whether its the culprit here or not.

**Comment by joshkoenig** [comment]
The mismatch is coming when there's an error that has `{}` as the message. We can switch that to an empty string to make it index, but it still won't be super useful. 

If we need to learn more about the failure states that generate this, that's fair. Perhaps we'll be able to do so after an initial beta release. :)

**Comment by joshkoenig** [comment]
Made a PR with some copy changes.

**Comment by pirog** [comment]
@joshkoenig i think we might have just duplicated work here ;)

and yah 100% on learning about the failure states. i _think_ most errors should be giving helpful messages and stack traces but the errors potentially bubble up through a ton of layers eg from scripts that run inside containers, to docker, to docker compose, to lando to PLD so i think we are going to have to just identify some of these "less chatty" pathways and slowly improve the error handling around them.

**Comment by joshkoenig** [comment]
Works for me for now. :shipit:

**Comment by pirog** [comment]
Awesome. Makes sense. 

I'm going to change the default "stack" and "message" to 1.) the correct type 2.) a helpful string so eg "no error message/stack provided" so we can better isolate error pathways to improve using the data we collect
