### ISSUE TITLE
Forwarded port value not displaying in GUI

### ISSUE THREAD

**Issue by aangelinsf** [pantheon-systems/localdev-issues#100]
I'm seeing two issues in the GUI of version 1.0.1.

First, when I perform a `lando info` I see:
external_connection: { host: '127.0.0.1', port: true} . 

I believe that should show me the port number that is randomly assigned, not `true.` In the GUI I see the port.

Second, when I added the following to .lando.yml:
services:
  database:
    type: mariadb
    portforward: 3600

and I perform a `lando info` I see:
external_connection: { host: '127.0.0.1', port: '3600' },

Which is correct. However, the GUI does not show that port; it still shows the randomly assigned port.

I was able to successfully connect to the mariadb container with SequelPro using 127.0.0.1 and port 3600.

**Comment by pirog** [comment]
@aangelinsf while Localdev uses Lando code at its core Lando and Localdev are, for all intents and purposes different tools. This means that you cannot control the functionality and features of a Localdev app with a `.lando.yml`.
