### ISSUE TITLE
Can we get an option to only pull the database and code added? 

### ISSUE THREAD

**Issue by ghost** [pantheon-systems/localdev-issues#102]
I have multiple duplicate Drupal projects going on at the same time and as a result I need multiple environments/branches/etc but in order to pull a site down it downloads EVERYTHING including images, etc. which I have already downloaded with the other environments. It would be nice to just pull what I want instead of requiring pulling everything. The images/etc I have to download makes pulling in the site take several hours because we have so many images. I could easily copy/paste the files over on my computer, but instead I'm stuck waiting several hours for it to process.

**Comment by pirog** [comment]
@Jingles1987 as of Localdev 1.1.0 there are "advanced initialization options" that let you skip pulling down files:
![image](https://user-images.githubusercontent.com/713424/135896218-1295b6e2-12f6-4fc7-85f2-86981a4d3669.png)
