### ISSUE TITLE
Settings error, Settings version is too high for this application.

### ISSUE THREAD

**Issue by joe-westcott** [pantheon-systems/localdev-issues#108]
When I fire up the latest version of Localdev, Version 1.1.0 (1.1.0.1035), the following error appears and blocks me from using Localdev:

> **Settings error**
> Settings version is too high for the application. Use the latest version or reset to factory defaults to continue.
> [ Reset Docker to factory defaults ] [ Diagnose & Feedback ] [ Exit ]

<img width="598" alt="localdev-docker-settings-error" src="https://user-images.githubusercontent.com/13838392/120550113-70e41680-c3c2-11eb-8528-d9d90d542e7b.png">

When I select the option to Reset Docker, a modal appears with the following status message, and it fails to complete its task even after several hours.

> **Reset Docker to factory defaults**
> Resetting factory defaults

<img width="598" alt="localdev-docker-resetting-fails-to-complete" src="https://user-images.githubusercontent.com/13838392/120550131-75103400-c3c2-11eb-9ad9-1f7ea44c7e4a.png">

**Comment by joe-westcott** [comment]
Please note that this issue is different than https://github.com/pantheon-systems/localdev-issues/issues/106

In that issue, Docker is forcing updates. In this issue, I let Localdev install its preferred version of Docker, and the system gets stuck in this loop despite that.

I'm able to fully uninstall Docker and try again, but the system keeps getting stuck in this loop.

If I intentionally install the latest version of Docker, then I don't get this loop; instead, Localdev simply fails to work when I start any local env.

**Comment by joe-westcott** [comment]
Insanity might be trying to same thing multiple times and expecting different results, but @girlg33k shared that reinstalling Docker and skipping the compatibility check solved the problem for her, so I tried those steps again just now ... and somehow it worked this time.

Not sure what's different this time, but if it matters, I'm running Docker version 3.3.3 (64133).

**Comment by conantp** [comment]
@joe-westcott - I've experienced this scenario - it happens when the Docker settings file version is higher than the currently installed version. Unfortunately, there's no way to get rid of the settings file in that scenario, so you have to re-install a current version of Dockeer, then do a full removal of Docker (which removes the settings), then allow LocalDev to re-install an older version. It's the worst!

**Comment by abigailthomasHB** [comment]
@conantp currently stuck in this situation. How do you do a full removal of Docker?
