### ISSUE TITLE
Site list incomplete for users with large numbers (300+) of sites

### ISSUE THREAD

**Issue by sixty7ss** [pantheon-systems/localdev-issues#11]
Only 40-50 sites out of ~300 are available to localdev. Feel free to reach to our organization admins at Digital Deployment for more details.

**Comment by bwood** [comment]
Going out a on a limb here because I haven't yet found any info describing the technology that powers LocalDev...but seems like a good possibility that this problem is related to the same API call discussed in this Lando issue: https://github.com/lando/lando/issues/988

**Comment by joshkoenig** [comment]
Thanks for surfacing this. The initial target persona for Localdev is developers who find engaging with Pantheon challenging absent a GUI, so we aren't going to initially prioritize the needs of customers with 100+ sites. Obviously your use-case matters a lot, but the mission for LocalDev 1.0 is democratizing access to the platform, so we are focused on more entry-level adopters first.

That said, it does look like an issue that could be resolved via the underlying Lando integration. We can certainly track it here as well for completeness.
