### ISSUE TITLE
Local access to drush/wpcli

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/localdev-issues#13]
Is it possible to have local access to drush/wpcli as it is a useful tool in local development?

**Comment by joshkoenig** [comment]
@carl-alberto yes this should be easily possible; how would you prefer to have this work?

**Comment by carl-alberto** [comment]
Thanks @joshkoenig, maybe something like this:

https://screencast.com/t/llPQA4Zqqc

There can be a copy & pasteable command or a button to open up terminal if that is possible

**Comment by joshkoenig** [comment]
This question has come up often in early user feedback.

**Comment by joshkoenig** [comment]
We're going to explore a "Open in terminal" button.
