### ISSUE TITLE
Database doesn't seem to be connected

### ISSUE THREAD

**Issue by awakash** [pantheon-systems/localdev-issues#14]
After seeing a list of sites within Localdev, and opening the specific local site, I get directed to the install page. After hitting 'Pull' tab and 'Pull Database' , then the Pull button, I get an updated that it's completed but when going to the local site, I'm still seeing the install page. Any ideas why I'm not seeing the site? Our db is about 240MB.
Note: not sure if it's related but our files directory is 80GB; even though I'm excluding pulling files, could it be related?

**Comment by joshkoenig** [comment]
Are you able to connect directly to the DB and see what state it is in?
