### ISSUE TITLE
Integrate with Multidev

### ISSUE THREAD

**Issue by royboy789** [pantheon-systems/localdev-issues#15]
Just got it connected to a site we have going, and we are working in a multidev. I was able to use cli to switch branches, but not sure that actually did anything. Would be nice if the local UI let you switch easily between multidev instances (if they exist).

**Comment by joshkoenig** [comment]
Hey Roy - this is "works as intended" for the moment. Multidev is not (yet) integrated with Pantheon Localdev. That will be added to a future release for sure though.
