### ISSUE TITLE
0.4.0 machine token doesn't allow copy/paste submission

### ISSUE THREAD

**Issue by elliottpost** [pantheon-systems/localdev-issues#16]
Upon installing `0.4.0` and copy/pasting my machine token from Pantheon website into the field for first-time setup, it doesn't allow me to submit. When I fill the field with extra garbage characters, I can then submit and the request will, of course, fail. After the first failed attempt, the submit button is unlocked so I can erase the contents and copy/paste the correct field as expected.

**Comment by joshkoenig** [comment]
Hey Elliott,

Can you double-check this for us? We're up to `0.4.2` now, but we are unable to replicate a copy/paste problem on our end. 

It is expected that the submit button is blocked until there are 45 characters of data, which is the length of a machine token. If your initial paste isn't getting you the whole token, is it possible that you didn't copy the whole thing?

**Comment by fembuelita** [comment]
Hi Josh, thanks for getting back to me. I also updated to `0.4.2` and I can no longer re-create the issue. I'm _fairly_ certain I was copying the entire string -- I tried several times and even at one point manually typed it in to see if that was the issue. In any case, whether it was a weird one-time glitch or an actual bug it appears to be resolved now. I'll close the ticket.
