### ISSUE TITLE
Wrong url showing for sites that use custom lando file with PMA service

### ISSUE THREAD

**Issue by fembuelita** [pantheon-systems/localdev-issues#19]
Lando version: `0.4.2`

When a lando with a PHPMyAdmin service file exists in the repository, the URL that localdev assigns to the site is incorrect. I'm not sure if a custom lando file is supported (see #18). If it isn't, you can probably record this as a known limitation and not resolve but just close this ticket and #18.

![pma_localdev](https://user-images.githubusercontent.com/3232219/60988129-9e280700-a308-11e9-96cd-6d8a8d651834.jpg)

In the custom lando file (shown in #18), there is a PMA service available as a subdomain of the actual lando app subdomain, ie:

Lando app: mysite.lndo.site
PMA: pma.mysite.lndo.site

And when running localdev it picks up the PMA URL instead of the app URL.

**Comment by joshkoenig** [comment]
Hey Elliot -

This may be an issue when your site already has a Lando config file. This isn't something we've aimed to support. All localdev hostnames should be on the `pantheonlocal.com` subdomain.

**Comment by fembuelita** [comment]
No worries. I assumed custom lando support may not exist yet, but thought I'd log this anyway. Up to you if you prefer to keep this open or not, @joshkoenig.

**Comment by pirog** [comment]
@elliottpost i think this is likely addressed by the thread/conclusion over in #18
