### ISSUE TITLE
Cloning development site locks up

### ISSUE THREAD

**Issue by RayHollister** [pantheon-systems/localdev-issues#21]
![image](https://user-images.githubusercontent.com/369131/61092101-e3386000-a412-11e9-8ba2-491b8fac0a75.png)
This is a fairly tiny WP install, and it has been stuck here for about an hour. I have previously uninstalled and reinstalled Localdev prior to this.

**Comment by joshkoenig** [comment]
Thanks for the bug report! Also, thanks for continuing to try to make it work.

Looking through the error logs, I see a report from Localdev that it cannot locate Docker, which will definitely prevent it from working properly.

Can you tell me more about how you have Docker installed? At a minimum it'd be good to know where it lives. For instance, on my system:

```shell
joshk@MBP1313-0103 ~$ which docker
/usr/local/bin/docker
joshk@MBP1313-0103 ~$ ls -la /usr/local/bin/docker
lrwxr-xr-x  1 joshk  staff  54 Jun 25  2018 /usr/local/bin/docker -> /Applications/Docker.app/Contents/Resources/bin/docker
joshk@MBP1313-0103 ~$
```

Thanks!

**Comment by RayHollister** [comment]
Rays-MBPr:~ rayhollister$ which docker
/usr/local/bin/docker
Rays-MBPr:~ rayhollister$ ls -la /usr/local/bin/docker
lrwxr-xr-x  1 rayhollister  staff  54 Jul  4 20:27 /usr/local/bin/docker ->
/Applications/Docker.app/Contents/Resources/bin/docker
Rays-MBPr:~ rayhollister$

- Ray Hollister

**Comment by joshkoenig** [comment]
Thanks Ray. We'll have to continue debugging.
