### ISSUE TITLE
Allow toggle for reverse proxy cache

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/localdev-issues#24]
Given the goal of supporting people who are on a WebOps learning curve, the presence of a reverse proxy cache (simulating the Global CDN) could introduce unnecessary confusion as part of a first time user experience.

We might want to make this a configurable toggle, with the default being "off" under the assumption that most people will want to dev/debug Global CDN integration in an online environment.

**Comment by joshkoenig** [comment]
Adding this to the next release target.

**Comment by pirog** [comment]
Adding some notes here to improve this a bit before we cut the next release

* We _should_ be able to make use of `lando rebuild`s ability to target a _specific_ container for rebuild. If we can do this it should make toggling significantly faster
* If you create a site, toggle the edge on, destroy the site, recreate the site, the toggle indicator shows that the edge is on when in fact it is off. guessing we are just not wiping the config slate clear on a destroy.
