### ISSUE TITLE
Error if software is closed/restarted while destroying a site

### ISSUE THREAD

**Issue by blake-pritchett** [pantheon-systems/localdev-issues#25]
Clicked to destroy a site and not thinking about it closed the software. Opened it back up and the site was still there. Clicked destroy again, throws an error and won't destroy the site now. Had to open to browse where the files are stored and delete them manually, which resolved the issue and made localdev realize the site was deleted from local.

**Comment by joshkoenig** [comment]
Thanks for finding a way to break things! We should probably find a way to make the "destroy" option more robust, and automatically escalate to "kill it with fire" if there are errors during cleanup. 😜

**Comment by pirog** [comment]
@blake-pritchett @joshkoenig in the forthcoming `0.6.0` release this scenario should be handled more gracefully eg you now cannot close PLD if it detects active ongoing processes and if you decide "i dont care" and force quit PLD will now clean up better on relaunch
