### ISSUE TITLE
Broken link to GitHub on help page

### ISSUE THREAD

**Issue by chicagomom** [pantheon-systems/localdev-issues#27]
On the localdev Help tab, the link to the localdev repository on GitHub gives 404 error.
![image](https://user-images.githubusercontent.com/993428/63173593-d4daf680-c005-11e9-93a5-31d9bffc011a.png)

**Comment by pirog** [comment]
nice @chicagomom! Good catch!

This should be fixed in the forthcoming `0.6.0`
