### ISSUE TITLE
Stuck at Step 3 - Booting Local Environment

### ISSUE THREAD

**Issue by ghost** [pantheon-systems/localdev-issues#28]
I tried searching for this on here and the Pantheon forums, but I just did a clean new install of Localdev and got all logged in and started downloading my site. It's a D8 site that is basically new, it's not big at all. But Localdev is essentially stuck at step 3 - booting local environment - and has been for about an hour. Does it typically take this long? Any way I can troubleshoot this? Thanks!

**Comment by dwainm** [comment]
Not sure if there may be an authorization issue causing it to remain stuck, but I've been waiting on this for more than an hour.

**Comment by carlospazucsb** [comment]
I'm experiencing the same issue. It's been stuck for more than two hours. Were you ever able to fix this issue?
