### ISSUE TITLE
Sites don't work after updating.

### ISSUE THREAD

**Issue by dficker** [pantheon-systems/localdev-issues#30]
I just updated from 0.5.0 to 0.5.1.

After I did so, none of my local sites worked. I would just get a "404 page not found" error on any URL for the site.

If I destroyed the site and pulled it down again, then the site would work again.

Thanks,

Dan Ficker

**Comment by carl-alberto** [comment]
Encountered a similar case earlier. Hopefully, we'll have a troubleshooting or upgrade guide publicly available soon

**Comment by mikemilano** [comment]
After upgrading to `0.5.1` I noticed my app had a 404 page while the localdev GUI showed it to be "Running". I was able to correct it by:

- Select the App
- At this point it shows "Running", but I had a 404
- Clicked the "Running" dropdown and selected "Stop"
- Then clicked it again to select "Start"
- At this point, the site loads in the browser OK

Once it was running, I did an update to `0.5.2-beta.0`. After the update was installed, it was still running OK.

I suspect if there's an issue, it was introduced in the `0.5.0` release as the latter releases were primarily GUI changes... at least nothing at the Lando level.

**Comment by jleetaylor2020** [comment]
Tix: https://pantheon-systems.desk.com/web/agent/case/264642

Dashboard: https://admin.dashboard.pantheon.io/sites/aca2ee71-b35d-4935-9a7a-9d3ee74d7788#dev/code

Related issue this morning and am working to resolve with the customer and his localdev (latest localdev + latest Docker installed on local machine) showing repeated 404 error

**Comment by trvswgnr** [comment]
I am also getting 404 errors after updating.

**Comment by mikemilano** [comment]
Observation: This is the state Localdev is in when you restart Docker after working on a site. Sites show they are Running, but their containers are not stopped. One thought is that we could check container states on startup to sync up the UI.

I also suspect this is only an issue updating from version `0.5.0`.

It would be helpful to know from when this occurs out in the wild:
- Does stopping and starting the app resolve the 404?
- Does this happen when upgrading from a version higher than `0.5.0`, from a state where the app was running well just before the upgrade?
