### ISSUE TITLE
Install SSL certificate

### ISSUE THREAD

**Issue by westonruter** [pantheon-systems/localdev-issues#32]
I got a certificate error when trying to access a local site I pulled down. Shouldn't Localdev be facilitating the installation of a certificate for `*.pantheonlocal.com`?

**Comment by mattbeck** [comment]
+1

**Comment by diegovogel** [comment]
+1
I can't use my password manager with Localdev sites because of this.

**Comment by pirog** [comment]
I can definitely confirm this and we are now tracking internally

**Comment by joshkoenig** [comment]
Apologies all - will have a release out shortly to fix this.

**Comment by rv-bnowak** [comment]
Was there a fix issued for this? I believe I'm still seeing this in 1.0.1 (1.0.1.1023)
