### ISSUE TITLE
Localdev wont pull my repository from Pantheon

### ISSUE THREAD

**Issue by victorsingh** [pantheon-systems/localdev-issues#37]
When I click the yellow "Pull for local development" button, I reach the Step 1 of 4: Cloning site code with Git step on the loading, screen, but instead of seeing my pulled repo, I get sent back to the "Clone your development site" view containing the yellow "Pull for local development" button I had originally clicked on.

Looking at localdevs console, I am currently getting the following error 

`/Applications/Localdev.app/Contents/Resources/app.asar/node_modules/lando/lib/shell.js:14 curl: (1) Protocol "ssh" not supported or disabled in libcurl
`

I have checked port 2222 on my machine and theres nothing running on it. Not sure why I'm consistently seeing this issue. I have not been able to successfully clone my Pantheon repo

**Comment by jon4896** [comment]
I am also experiencing this issue
