### ISSUE TITLE
Incompatible with Docer version 2.2.x

### ISSUE THREAD

**Issue by rfair404** [pantheon-systems/localdev-issues#41]
I had docker installed previous to installing Localdev. I was on the latest version (2.2.something) - when I open Localdev I get error `Error: spawn /Applications/Docker.app/Contents/Resources/bin/docker-compose EACCES`

In doing some research I found this issue in the Lando repo: https://github.com/lando/lando/issues/1941 - it seems that some of the docker-compose files were moved in 2.2.x - uninstalling Docker and installing version 2.1.0.4 per this comment: https://github.com/lando/lando/issues/1941#issuecomment-576775958 seems to do the trick. 

Might be helpful for others who are having issues to be aware.

**Comment by scotthooker** [comment]
+1

**Comment by cameroncondry** [comment]
Just to add, when installing and running Docker version 2.1.0.4 there is an immediate prompt asking to update to the latest version. Be sure to use the skip or remind later buttons to avoid the issue with Lando and subsequently Pantheon LocalDev.

**Comment by irinaz** [comment]
I have the same problem.  rfair404, thanks for finding solution!

**Comment by cgrymala** [comment]
+1

**Comment by hellodaylight** [comment]
+1 same here. I updated Docker on first try, thinking it would be fine. Uninstalling Docker 2.2.x and running the Localdev installer again, this time skipping the option to upgrade Docker, did the trick.

**Comment by andyhawks** [comment]
Downgrading Docker is not a solution. This needs fixed in Lando.

**Comment by pirog** [comment]
This will be fixed in the next Lando release and will include better Docker version handling in general. Once that happens we can update the version of lando in Localdev and add the needed UX

**Comment by pirog** [comment]
There is a new Lando release which now supports this. Should be available on the Pantheon edge release channel later today and hopefully the stable release channel later this week or earlier next week!

**Comment by pirog** [comment]
This is now available on the latest release if you use the Localdev `beta` channel
