### ISSUE TITLE
Repo won't run destory command. 

### ISSUE THREAD

**Issue by ChrisB55** [pantheon-systems/localdev-issues#42]
I got an error message trying to pull a  D8 site for localdev development. After the failed pull,  the destroy command was the only option but it won't destroy the site and gets stuck there. Cancelling the destroy has no effect. 

version 0.7.0

**Comment by hellodaylight** [comment]
@ChrisB55 I had the same issue. See issue #41 for what fixed it in my case (uninstalling Docker 2.2 and running LocalDev again but SKIP the Docker upgrade. You need Docker 2.1.0.4 for localDev to work).

**Comment by pirog** [comment]
Closing this in favor of #41 !
