### ISSUE TITLE
Installed New Version of LocalDev and everything is broken

### ISSUE THREAD

**Issue by eyecre8** [pantheon-systems/localdev-issues#44]
![Screen Shot 2020-02-07 at 4 51 47 PM](https://user-images.githubusercontent.com/39813417/74069169-734f7f80-49cb-11ea-9272-cd466e9239d0.png)
I am on Docker 2.2.0.0
I am on LocalDev 0.7.0

**Comment by carl-alberto** [comment]
Another customer having same issues already tried to reinstall LocalDev 0.7.0 by:
- deleting ~/.pantheonlocaldev
- reinstalled docker 2.2.0.3 stable channel
- Redownloaded 0.7 Localdev
OS: Catalina 10.15.3 

Error.log says
```
{"level":"warn","message":"Docker has started but we are waiting for a connection","timestamp":"2020-02-12T22:49:41.628Z"}
{"level":"warn","message":"You should be good to go momentarily!","timestamp":"2020-02-12T22:49:41.629Z"}
{"context":"localdev","message":"spawn /Applications/Docker.app/Contents/Resources/bin/docker-compose EACCES","stack":"Error: spawn /Applications/Docker.app/Contents/Resources/bin/docker-compose EACCES\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)\n    at onErrorNT (internal/child_process.js:407:16)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","type":"error","level":"error","timestamp":"2020-02-12T22:49:50.294Z"}
```

**Comment by carl-alberto** [comment]
Hi Folks

Please try out the Docker Desktop Community 2.1.0.5

https://download.docker.com/mac/stable/40693/Docker.dmg and see if that fixes the issues

**Comment by mistcat** [comment]
Yeah it appears that Localdev 0.7 is not compatible with Docker 2.2.0.3 (42716) I get this same error with Catalina 10.15.3.  Alas!

**Comment by tarnus** [comment]
Looks to be an issue with lando not supporting docker 2.2  see this lando bug report:
[https://github.com/lando/lando/issues/1941](https://github.com/lando/lando/issues/1941)

**Comment by carl-alberto** [comment]
Please comment out if these steps worked out in your end or not, if not, please post some helpful logs from ~/.pantheonlocaldev/logs/error.log. Thanks!

**Comment by pirog** [comment]
Closing this in favor of #41
