### ISSUE TITLE
Feature Request: Don't Pull Media Files

### ISSUE THREAD

**Issue by taupecat** [pantheon-systems/localdev-issues#55]
I have a site with a large Media Library that I needed to fix a small PHP bug on, but the time it was taking to pull down the media assets (not to mention the space it was going to take on my local hard drive) made Localdev just not practical. So I ended up pulling the code directly with git and running it locally on the Vagrant setup I used prior to moving to Localdev.

I'd really like a way to not have to pull down the media library (or even just capping it at a certain number of MB) when cloning a site to Localdev. I don't really need photos from 2014 in order to fix a PHP bug.

Thanks!

**Comment by pirog** [comment]
@taupecat totally agreed and we actually already have an internal ticket to add this, and other options, to the site initialization

**Comment by taupecat** [comment]
Is there any update on this? Once again, I've tried pulling down a site with a large amount of high-resolution images. It _looked_ as if, after some time, the images finished pulling down (running a `du -hd` on the uploads directory hit a max number and didn't go higher), but the site never actually came up, even after waiting for over half an hour. Launching the "show detail" window (admittedly, rather belatedly) showed _no_ log messages. I even tried opening the site in a browser, and the site never loaded, just sat there with the circular animation going in the Chrome tab.

Finally, I had to give up and cancel the whole thing. I guess this is another site I'm going to go back to Vagrant to work on. 😞

**Comment by bowenac** [comment]
I think a nice option would be the ability to point uploads to a production url or some other pantheon environment. This is pretty easy to do via .htaccess but I do not think pantheon local uses .htaccess as I tried a config I have used for other sites, local environments and it didn't work.

**Comment by pirog** [comment]
For those who end up here. This feature was added in Localdev 1.1.0 and looks like this if you click on the "advanced initialization options" when pulling down an environment:
![image](https://user-images.githubusercontent.com/713424/135896384-d7d0d2a3-b2d0-47dc-b945-7bbe3b676422.png)
