### ISSUE TITLE
LocalDev: codebase changes are reflected on the local site only after restart

### ISSUE THREAD

**Issue by gkapsal** [pantheon-systems/localdev-issues#71]
Every change i make in the codebase in drupal is not being reflected if i dont restart the instance. 

I noticed that if i put die in index.php on root folder it works before drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);
if i put die after that line, it doesnt see the change. 

Mac OS 10.15.5
Docker 2.3.0.3
LocalDev 0.10.1
Drupal 7 (on latest version updated)

**Comment by pirog** [comment]
@gkapsal if the change before the drupal bootstrap is reflected then the most likely explanation is that drupal caching is turned on and this is preventing the edit from being reflected
