### ISSUE TITLE
Warning: Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /app/wp-content/plugins/wp-redis/object-cache.php on line 1209 Warning: WP Redis: php_network_getaddresses: getaddrinfo failed: Name or service not known in /app/wp-content/plugins/wp-redis/object-cache.php on line 1388

### ISSUE THREAD

**Issue by wernerglinka** [pantheon-systems/localdev-issues#78]
After installing object-cache.php and the WP Redis plugin, my local WP site shows this warning:

**Warning: Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /app/wp-content/plugins/wp-redis/object-cache.php on line 1209 Warning: WP Redis: php_network_getaddresses: getaddrinfo failed: Name or service not known in /app/wp-content/plugins/wp-redis/object-cache.php on line 1388**

The Pantheon dev site seems to be fine. Status in the Pantheon backend doesn't show any warnings. 

Has anybody seen this and/or k ows how to fix this?

**Comment by pirog** [comment]
@wernerglinka i dont think `redis` is on by default in localdev so you'll need to activate it 
 in the advanced tab and make sure your local settings are not overriding any pantheon specific config for redis.

**Comment by pirog** [comment]
@wernerglinka closing this in favor of #112
